name: Swift

on: [push]

jobs:
  tests:
    name: Unit Tests
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd Rubicon && swift test --enable-code-coverage
