name: Swift

on: [push]

jobs:
  tests:
    name: Unit Tests
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        xcode-version: '14.3'
    - name: Build
      run: swift test --enable-code-coverage
